# With Constraints
# 
# The following workflow is a example of a workflow
# narrative(intent.i) -> review(code.1) -> [ repair(code.1 + code.2) | LGTM(stop) | clarification(proposal) ] 
#                                      -> clarification(proposal.a) -> response(proposal.a)
#                                      -> review((intent.i, proposal.a), code.3) -> repair(code.3 + code.4)
#                                      -> review((intent.i, proposal.a), code.5) -> clarification(proposal.b)
#                                      -> clarification(proposal.b) -> response(proposal.b)
#                                      -> review((intent.i, proposal.a, proposal.b), code.7) -> repair(code.7 + code.8)
#                                      -> review((intent.i, proposal.a, proposal.b), code.15) -> LGTM(stop)
# 
# This workflow could reoughly be modeled with a WHILE loop
# the while loop would continue until:
#  LGTM(stop) 
#  or a constratin is met, e.g. max number of iterations, max number of repairs, max number of clarifications, etc.
# 
# So if we represened it as a funciton block "Intent(prose) -> Review(Cfg, Code) -> Action" 
# Where Action is the UnionType of Repair(OriginalCode + NewChanges) | LGTM(stop) | Clarification(proposal)
# 
# Then perhaps if we made a parallelized version of this function block
# each funciton call would be a stacked PR
# 
# which is akin to a FanOut/FanIn pattern
# so the parallel node, with numerous configs in represented, is a type of FanOut (or a bakeoff)
# 
# Then we need a Fan In Pattern to collect the results of the parallel nodes
# maybe the config needs a parallel key-word in the vocab?
# maybe we can represent the parallel node with just an array? or with a map funciton?
#
# But then we will need to represent a reducer...
# Maybe with a "selectMax" keyword? or a 'keepMax' keyword?
# The issues is really that we are mostly setting a strucutral choke point for how many branches continue.
# We cant say much about the branches. 
# So the Reviewer/chooser needs to pick the best branches up to K (where we recommend not exceeding k=4 for now)
#
# From thse best K branches then we need a "reduce" keyword? or "fold" or "merge" keyword?`
# that actually gets us to a best case code generation. that maintains the intent, and has survived scutiny of other models.
#
# So then in the ollama exmaple, many models, each after ther first. So possibly iterating with a fast cheap model, 
# then promoting to a heavier more thoughtful model, 
#
#
# So that might need a "step" keyword? or "step": set: model:____ while: conditions: [!LGTM, Constraints.continue] => [reivew, repair, clarify]
# Maybe all this points us to a Dhall DSL for the config? who knows...
# 
# ## Cconstraints:
# ### Repo Constraints:
# constraints applied to the rpeo as a whole. Such as "monthly spend limit"?
# ### PR Constraints:
# constraints applied to the PR as a whole. Such as "max number of lines of code"?
# ### Wave Constraints:
# constraints applied to the wave as a whole. Such as "max number of waves"?
# ### Review Constraints:
# constraints applied to the review as a whole. Such as "max number of reviews"?
# ### Repair Constraints:
# constraints applied to the repair as a whole. Such as "max number of repairs"?

